# -*- coding: utf-8 -*-
"""operator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ph3OHH6KftCiyAk9oN6u9YSM4X1XAp07

บวกกัน x+y

ลบกัน x-y

คูณกัน x*y

หารกัน 
แบบที่ 1 : x/y (ไม่ลงตัวจะเป็นเลขทศนิยม)
แบบที่ 2 : x//y (เอาผลหาร ไม่เอาเศษ ไม่เอาเลขหลังทศนิยม หรือปัดทศนิยมทิ้งทั้งหมด) เช่น 5/3 ได้ 1.6666666666666667 แต่ 5//3 = 1
แบบที่ 3 : x % y (เอาแต่ตัวเศษ หรือ mod) เช่น 5 % 3 = 2 (ได้เศษ 2)
แบบที่ 4 : divmod(x,y) [เอาทั้งผลหาร ทั้งเศษ] เช่น divmod(5,3) = (1,2)

ยกกำลัง 
แบบที่ 1 x**y = x^y
หรือ แบบที่ 2 pow(x,y) = x^y

-----------------------------------------------------

-5 = 5
+5 = 5
abs(-5) = 5 >>>>> absolute
int(5.2) = 5
float(5) = 5.00



---------------------------------------------------------

key in s containment check #key อยู่ใน s
key not in s non-containment check #key ไม่ได้อยู่ใน s
s1 == s2 s1 is equivalent to s2
s1 != s2 s1 is not equivalent to s2
s1 <= s2 s1 is subset of s2
s1 < s2 s1 is proper subset of s2
s1 >= s2 s1 is superset of s2
s1 > s2 s1 is proper superset of s2
s1 | s2 the union of s1 and s2
s1 & s2 the intersection of s1 and s2
s1 − s2 the set of elements in s1 but not s2
s1 ˆ s2 the set of elements in precisely one of s1 or s2
"""