# -*- coding: utf-8 -*-
"""ปัดทศนิยม.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ph3OHH6KftCiyAk9oN6u9YSM4X1XAp07
"""

# ปัดทศนิยม
a = 1.345623242343

print('{:.2f}'.format(a)) #1.35

b= 1.421455
print('{:.2f}'.format(b)) #1.42