# -*- coding: utf-8 -*-
"""ลอง %.1f.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ph3OHH6KftCiyAk9oN6u9YSM4X1XAp07
"""

i = 0
for i in range(i,6,1): #i = 0 , 0-5 
            print('%.1f'%i,end= ', ') #0.0, 1.0, 2.0, 3.0, 4.0, 5.0,

