# -*- coding: utf-8 -*-
"""ลอง tuple.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ph3OHH6KftCiyAk9oN6u9YSM4X1XAp07
"""

# tuple uses () to store datas // unchangeable
coordinates = (4,5,4)
print(coordinates)
print(len(coordinates))

# make a tuples must use 2 ()
thistuple = tuple(('apple','banana'))
print(thistuple)