# -*- coding: utf-8 -*-
"""ลอง funtions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ph3OHH6KftCiyAk9oN6u9YSM4X1XAp07
"""

def sayHi(a): #a = 'wow'
    print("Say Hi like : " + a)  #a = 'wow'

sayHi('wow') #print wow ต่อจาก Say Hi like : 

#Say Hi like : wow