# -*- coding: utf-8 -*-
"""3 Sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BZvdaUfZ2JcGMP9tvtGjO5Ybf_DSbOTn
"""

"""
จงเขียนฟังก์ชันเพื่อหาผลรวมของ 3 พจน์ใดๆใน Array ที่มีผลรวมเท่ากับ 0 สำหรับ Array ที่มีข้อมูลข้างในเป็นจำนวนจริง ***Array ต้องมีความยาวตั้งแต่ 3 จำนวนขึ้นไป***
"""
inp = list(map(int,input('Enter Your List : ').split())) #******** จำ
ans = [] #ประกาศตัวแปร ans เป็น list ว่าง ๆ
temp = [0,0,0]
for i in range(0,len(inp)): 
  for j in range(i+1,len(inp)):
    for k in range(j+1, len(inp)):
      if inp[i]+ inp[j] + inp[k] == 0:
        temp[0] = inp[i]
        temp[1] = inp[j]
        temp[2] = inp[k]
        temp.sort() #เรียงลำดับจากน้อยสุดไปมากสุด Source: https://www.w3schools.com/python/python_lists_sort.asp
        if temp not in ans: 
          ans.append(temp.copy) #copy จาก temp มาใส่ใน list ของ ans
if len(inp) > 2:
  print(ans)
else :
  print('Array Input Length Must More Than 2')



