# -*- coding: utf-8 -*-
"""Simple OOP Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gEguhPJMg4jrPqF1JxYNzyj3MmyjBfUs
"""

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
จงเขียน Overloading Function สำหรับ Calculator class โดยที่มีรูปแบบ Code ดังนี้ (สามารถเพิ่มพารามิเตอร์ได้)

class Calculator :

    ### Enter Your Code Here ###

    def __add__(self):

        ###Enter Your Code For Add Number###

    def __sub__(self):

        ###Enter Your Code For Sub Number### 

    def __mul__(self):

        ###Enter Your Code For Mul Number###

    def __truediv__(self):

        ###Enter Your Code For Div Number###

x,y = input("Enter num1 num2 : ").split(",")

x,y = Calculator(int(x)),Calculator(int(y))

print(x+y,x-y,x*y,x/y,sep = "\n")

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""

class Calculator :
  def __init__ (self,num):
    self.num = num
  def __add__(self,a):
    return self.num +a
  def __sub__(self,a):
    return self.num - a
  def __mul__(self,a):
    return self.num*a
  def __truediv__(self,a):
    return self.num/a
  
x,y = input("Enter num1 num2 : ").split(",")

x=Calculator(int(x))
y= int(y)

print(x+y,x-y,x*y,x/y,sep="\n") #sep คือตัวที่ทำหน้าที่ ตรง "," การใช้ https://www.geeksforgeeks.org/python-sep-parameter-print/

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
เช่น
#code for disabling the softspace feature
print('G','F','G', sep='') ผลที่ได้ GFG
 
#for formatting a date
print('09','12','2016', sep='-') ผลที่ได้ 09-12-2016
 
#another example
print('pratik','geeksforgeeks', sep='@') ผลที่ได้ pratik@geeksforgeeks


print('G','F', sep='', end='')
print('G')

>>>>>> ผล GFG <<<<<<<<<


#\n provides new line after printing the year
print('09','12','2016', sep='-', end='\n')

>>>>>> ผล 09-12-2016 <<<<<<<<
 
print('prtk','agarwal', sep='', end='@')
print('geeksforgeeks')

>>>>>>> ผล prtkagarwal@geeksforgeeks <<<<<<<<<

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""