# -*- coding: utf-8 -*-
"""countdown.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10l3VZm2ntOmrHpHpDVusVJCq7qhqj2Nx
"""

print('*** Fun with countdown ***')
input = input("Enter List : ").split()
input = [int(i) for i in input] #ใส่เลขหลาย ๆ ตัว (เว้นวรรค)
count = int(0) #กำหนดให้เป็นค่า = 0 เป็น casting integer จาก string
countdown = [] #ประกาศตัวแปร list countdown
preans = []
anslist = []

for  i in range (0,len(input)):
  if i != 0: #ไม่เอาตัวที่ 0
    if input[i] == input[i-1]-1: #ตัวที่ i มากว่า ตัวที่ i-1 อยู่ 1 เช่น ตัวที่ 1 มีค่าเป็น 5 มากกว่า ตัวที่ 2 มีค่าเป็น 4 อยู่ 1
      countdown.append(input[i-1]) #ใส่ ตัวที่ i ของ list input ลงใน countdown
    else :
      countdown.clear #clear list ใน countdown
    if input[i] == 1 : #ถ้า input ตัวที่ i ใด ๆ มีค่า = 1
      count += 1 #นับ count
      countdown.append(1)
      preans.append(countdown.copy()) #copy list countdown มาใส่ใน list ของ preans
      countdown.clear() #clear list ของ countdown ทิ้ง
    
anslist.append(preans.copy()) #copy list ของ anslist
anslist.insert(0,count) #ใส่ count เข้ามาใน list ตัวที่ 0
print(anslist)