# -*- coding: utf-8 -*-
"""Election.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1brnkcIfVwWxGUDG36v_aA-azicc6qIe5
"""

"""""""""""""""""""""""""""""""""""
โรงเรียนดังประจำจังหวัดแห่งหนึ่ง จะมีการจัดการเลือกตั้งหาประธานนักเรียนคนใหม่ขึ้นในทุกๆปี โดยในปีนี้มีผู้เข้าแข่งขันสูงถึง 20 คน โดยกฤษฎาได้รับมอบหมายให้เป็นผู้นับคะแนนเลือกตั้งในปีนี้ แต่กฤษฎารู้สึกขี้เกียจนับคะแนนขึ้นมา จึงได้ไหว้วานให้คุณช่วยเขียนโปรแกรม ในการหาว่าผู้เข้าแข่งขันคนใดได้รับคะแนนสูงที่สุด

ข้อควรระวัง หากมีการเลือกเลขที่ไม่ตรงกับผู้เข้าแข่งขัน (1-20) จะนับว่าเป็นบัตรเสีย และถ้าหากทุกใบเป็นบัตรเสียจะถือว่าไม่มีผู้ชนะ
"""""""""""""""""""""""""""""""""""

print("*** Election ***")
number  = input("Enter a number of voter(s) : ")
voters = input("").split()
vote = []
negativeVote = []

for x in voters :
  if int(x)  > 0 and int(x) <= 20 : #ตัวแปร x in loop for
    vote.append(int(x)) 

if len(vote) < 1 or len(negativeVote) > 0:
  print("*** No Candidate Wins ***")

elif len(vote) > 0:
  print(max(set(vote),key=vote.count))