# -*- coding: utf-8 -*-
"""function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1brnkcIfVwWxGUDG36v_aA-azicc6qIe5
"""

"""""""""""""""""""""""""""""""""""
จงเขียนฟังก์ชัน 
def odd_list(alist):
โดยมีการทำงานดังนี้
     # คืนlist ที่มีค่าเหมือนalist แต่มีเฉพาะตัวที่เป็นจำนวนคี่
     # เช่นalist = [10, 11, 13, 24, 25] จะได้ [11, 13, 25]

โดยแก้ไขจากส่วนของคำสั่งต่อไปนี้


def odd_list(al):
    # เติมส่วนของคำสั่ง


print(" ***Function Odd List***")
ls = [int(e) for e in input("Enter list numbers : ").split()]
print(ls)
opls = odd_list(ls)
print("Input list : ", ls, "\nOutput list : ", opls)


แล้วแสดงผลดังตัวอย่าง

"""""""""""""""""""""""""""""""""""
def odd_list(al):
  ans =[]
  for x in al:
    if x % 2 == 1:
      ans.append(x)
  return ans

print(" ***Function Odd List***")
number = [int(e) for e in input("Enter list numbers : ").split()]
oddlist = odd_list(number)
print("Input list : ",number, "\nOutput list : ",oddlist)